Sfl filter mind
webonise/android-fitness pull request #170
Opened 2020-09-05 17:53 UTC by aniket-Webonise

2020-09-06 09:24 UTC, tejasalsi commented on app/src/main/java/com/sjana/fitness/view/feature/home/move/MoveFragment.kt
> +//                } else if (whichList == MOVELISTING) {
remove commented code

2020-09-07 06:28 UTC, tejasAlsi-Webonise commented on app/src/main/java/com/sjana/fitness/view/feature/home/move/MoveFragment.kt
> +//            }
remove this commneted code

2020-09-07 06:28 UTC, tejasAlsi-Webonise requested changes
remove commented code

2020-09-07 11:07 UTC, tejasAlsi-Webonise approved these changes

2020-09-07 11:07 UTC, merged