Yes no dialog
webonise/android-fitness pull request #171
Opened 2020-09-07 09:47 UTC by saurabhB-Webonise

2020-09-07 10:15 UTC, tejasAlsi-Webonise commented on app/src/main/java/com/sjana/fitness/view/feature/home/explore/valuefinder/YesNoVfDialogFragment.kt
> +class YesNoVfDialogFragment : BaseDialogFragment<ValueFinderViewModel>() {
No need of this class. This dialog is already present use that.

2020-09-07 10:19 UTC, tejasAlsi-Webonise commented on app/src/main/java/com/sjana/fitness/view/feature/home/explore/valuefinder/TopTenSelectedValueFragment.kt
> +                findNavController().navigateUp()
what is this logic for? two times navigate up. this is incorrect fix it.

2020-09-07 10:28 UTC, tejasAlsi-Webonise commented on app/src/main/res/layout/yesno_vf_dialog_fragment.xml
> +<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
remove this file as well

2020-09-07 10:29 UTC, tejasAlsi-Webonise requested changes
Check comments

2020-09-07 16:04 UTC, saurabhB-Webonise commented on app/src/main/java/com/sjana/fitness/view/feature/home/explore/valuefinder/YesNoVfDialogFragment.kt
> +class YesNoVfDialogFragment : BaseDialogFragment<ValueFinderViewModel>() {
done

2020-09-07 16:14 UTC, saurabhB-Webonise commented on app/src/main/res/layout/yesno_vf_dialog_fragment.xml
> +<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
done

2020-09-07 16:14 UTC, saurabhB-Webonise commented on app/src/main/java/com/sjana/fitness/view/feature/home/explore/valuefinder/TopTenSelectedValueFragment.kt
> +                findNavController().navigateUp()
done

2020-09-08 08:11 UTC, tejasAlsi-Webonise approved these changes

2020-09-08 08:12 UTC, merged